### ISSUE TITLE
Create Policy & Guidelines page

### ISSUE THREAD

**Issue by avspeed** [Code-the-Dream-School/ffprac-team4-front#21]
Create Policy & Guidelines page
The idea is to provide a page that shows the policy and a ACCEPT/ DECLINE the policy.

**Comment by AmirhosseinOlyaei** [comment]
https://www.figma.com/community/file/1248375255495415511
- [x] Open this file in your smartphone.
- [x] Click on Figma.
- [x] Sign in with your Google account.
- [x] When the License Agreement pops up, take a screenshot.
- [x] Place the image in our Figma

**Comment by AmirhosseinOlyaei** [comment]
Next:

- [x] Resize the image to the size of mobile frame. (make sure it keeps proportion.

1. In the Nav bar, click on Frame. 
2. One the Right Side Nav, click on Phone category.
3. Pick iPhone 13 & 14.
4. Resize the image to fit inside the frame.
5. When you got the actual size, then, take it out of the frame.

**Comment by AmirhosseinOlyaei** [comment]
Next,

- [x] Wireframe based on the mobile view
